project_id = "qihpywleopgrlvwcffvy"

[functions.scan-website]
verify_jwt = false

[functions.generate-article]
verify_jwt = false

[functions.generate-blog-post]
verify_jwt = false

[functions.test-cms-connection]
verify_jwt = true

[functions.fetch-keywords]
verify_jwt = true

[functions.generate-missing-images]
verify_jwt = false
